import type { Metadata } from "next";
import { business } from "../../lib/business";

export const metadata: Metadata = {
  title: "Review card (print me)",
  robots: { index: false, follow: false },
};

// The QR encodes yoursite.com/review, which then bounces to Google reviews.
// The image is generated by a free QR service purely so you can PRINT this card —
// it isn't a runtime dependency of the customer-facing site.
export default function Page() {
  const reviewUrl = `${business.domain}/review`;
  const qr = `https://api.qrserver.com/v1/create-qr-code/?size=520x520&margin=8&data=${encodeURIComponent(reviewUrl)}`;

  return (
    <main style={{ background: "#fff", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: "24px" }}>
      <div style={{ width: "340px", border: "2px solid var(--ink)", borderRadius: "14px", padding: "30px 26px", textAlign: "center", background: "#fff" }}>
        <div className="mono" style={{ letterSpacing: "0.34em", color: "var(--brass)", fontSize: "0.7rem", marginBottom: 6 }}>ADAMS APPLIANCES</div>
        <div style={{ color: "var(--brass)", fontSize: "1.6rem", letterSpacing: "3px", marginBottom: 8 }}>★★★★★</div>
        <h1 className="display" style={{ fontSize: "1.7rem", fontWeight: 800, margin: "0 0 6px", color: "var(--ink)" }}>Happy with our service?</h1>
        <p style={{ color: "var(--slate)", margin: "0 0 18px", fontSize: "0.95rem" }}>Scan to leave a quick Google review — it means the world to a local family business.</p>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={qr} alt="Scan to review Adams Appliances" width={260} height={260} style={{ width: "260px", height: "260px", margin: "0 auto" }} />
        <p className="mono" style={{ color: "var(--slate)", fontSize: "0.62rem", letterSpacing: "0.1em", marginTop: 14 }}>{business.domain.replace("https://", "")}/review</p>
      </div>
      <style>{`@media print { header, footer { display: none !important; } }`}</style>
    </main>
  );
}
